### ISSUE TITLE
Want to update README.md and add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by sb-decoder** [LemonjamesD/Whiteboard#28]
I will be adding a contributors section in your readme which will be automatically updated when anyone contributes to your project.

**Comment by sb-decoder** [comment]
@LemonjamesD please add hacktoberfest label to the issue

**Comment by sb-decoder** [comment]
@LemonjamesD ,Can you share your email ID, I require it to be add to CODE_OF_CONDUCT.md file

**Comment by LemonjamesD** [comment]
lemonjameslem@protonmail.com
